export const SIMULATION_CONSTANTS = {
  RAMP_SECONDS: 60,
  MAX_LOAD_FRACTION: 2.0,
  MAX_EFFECTIVE_LOAD: 3.0,
  DEGRADED_AT: 70,
  SATURATED_AT: 90,
  CACHE_HIT_RATIO: 0.8,
  DB_POOL_PER_VM: 20,
  MAX_DB_CONNECTIONS: 100,
  WRITE_COST_FACTOR: 2,
  VM_WRITE_CPU_TAX: 0.3,
  BURST_CYCLE_SECONDS: 120,
  BURST_DURATION_SECONDS: 20,
  BURST_RAMP_SECONDS: 5,
  RPS_PER_VCPU: 80,
  QPS_PER_VCPU: 125,
  KBPS_PER_GBPS: 125_000,
  PAYLOAD_KB: { light: 10, medium: 100, heavy: 1024 },
  BANDWIDTH_CAPACITY_KBPS: {
    "Virtual Machine": 125_000,
    "Load Balancer": 250_000,
    "CDN": 1_000_000,
    "Object Storage": 500_000
  },
  CHAOS: {
    CRASH_DURATION: 30,
    CPU_SPIKE_DURATION: 20,
    CPU_SPIKE_BOOST: 45,
    MEMORY_LEAK_DURATION: 40,
    MEMORY_LEAK_RATE: 2.5,
    NETWORK_DELAY_DURATION: 25,
    NETWORK_DELAY_CPU_FACTOR: 1.6,
    DISK_FAILURE_DURATION: 35
  }
} as const;


export type SimulationConstantsType = typeof SIMULATION_CONSTANTS;